### PR TITLE
Added cBlockArea:CountNonAirBlocks API function.

### PR DESCRIPTION
**Pull request by madmaxoft**

### CODE REVIEW

**Comment by worktycho** [comment]
Why size_t?

**Comment by madmaxoft** [comment]
Why not? Is there a type that is more suited?

**Comment by worktycho** [comment]
int? Its not like this needs to be a 64 bit type on 64 bit systems.

**Comment by madmaxoft** [comment]
Just like the amount of data in the packet buffer is never gonna need more than 32-bits, yet still we use `size_t` for it.
Also, unsigned.

**Comment by worktycho** [comment]
Packet buffer code interacts with sizeof a lot so it make sense to have the same type as sizeof(). size_t is for size's of c++ objects. This is a count.

**Pull request merged**
