### PR TITLE
Added hooks HOOK_ENTITY_CHANGE_WORLD and HOOK_ENTITY_CHANGED_WORLD

### LINKED ISSUE #1435: HOOK_PLAYER_SPAWNED doesn't get called if player has been moved to world
Hey,

I am not sure if that is a bug.
There is a hook named HOOK_PLAYER_SPAWNED, that gets called if the player (re)spawns in the world where they are.

My thought is, if I move the player with the function Player:MoveToWorld("world"), then the hook HOOK_PLAYER_SPAWNED should be called, but that doesn't happen.

There is no other hook with that I can check if the player gets added to the world, for the function Player:MoveToWorld("world")

Thanks,
Seadragon91

### PR DESCRIPTION
**Pull request by Seadragon91**
This fixes #1435.
I wanted to add the lua description for the hooks. How can I add them?

### CODE REVIEW

**Comment by bearbin** [comment]
The description is in MCServer/Plugins/APIDump/apidesc.lua

Also, your build failed.

**Comment by Seadragon91** [comment]
To the hook files, is that really correct?
`The following paths are ignored by one of your .gitignore files:
MCServer/Plugins/APIDump/Hooks/OnEntityChangeWorld.lua
Use -f if you really want to add them.`

**Comment by bearbin** [comment]
Oh, sorry. The hook files are in the Hooks directory.

Your git change seems correct to me.

**Comment by Seadragon91** [comment]
Okay, I have boths hook files should I add then to the same commit? Or both files to a own commit?

**Comment by bearbin** [comment]
I don't think the commits need squashing, how they are at the moment is fine.

**Comment by madmaxoft** [comment]
Someone was too trigger-happy again.

The hooks are named badly. We use an `-ING` and `-ED` pair for pre- and post- hooks.

**Pull request merged**
