### PR TITLE
Don't verify certificate

### PR DESCRIPTION
**Pull request by worktycho**
Temporary Hot-fix for #2072

### CODE REVIEW

**Comment by bearbin** [comment]
Looks good. We need a proper fix but this should do for now.

**Comment by madmaxoft** [comment]
This is stupid, why not simply change the root cert?

**Comment by madmaxoft** [comment]
Also, it affects all SSL connections (even those by plugins), not only the Mojang one.

**Comment by SphinxC0re** [comment]
I agree. This is not even a *real* fix. We're just abandoning the real problem

**Comment by bearbin** [comment]
The problem is that the new certificate is a wildcard cert, so simply changing the root to the correct one does nothing. 

I agree that this isn't a proper fix, but nobody was going to get one done last night.

**Comment by worktycho** [comment]
This was a emergency fix, so that people could start using the server again. I agree it is compleatly broken, but we'd been trying to get a proper fix out for most of the afternoon, and it didn't look like we'd get one soon, so I put this in as a quick change that would allow the server to accept logins until we got the wildcard cert working.

**Pull request merged**
