### PR TITLE
Updated copyright/license date to 2015 for new year.

### PR DESCRIPTION
**Pull request by benhc123**
Updated copyright/license date to 2015 for new year.

### CODE REVIEW

**Comment by bearbin** [comment]
I think this should really be changed so it has copyright xxxx to xxxx rather than just 2015, as most of the code hasn't actually been modified in 2015

**Comment by madmaxoft** [comment]
And do we need the date at all? It's something that will only need changing, can't we remove the year altogether?

**Comment by bearbin** [comment]
I'm petty sure that it's better to have no year than an incorrect one, so
removing it would be fine with me.

**Comment by tigerw** [comment]
@benhc123, want to update the PR?

**Comment by bearbin** [comment]
Fixed in master, x to x.

**Pull request closed without merging**
