### PR TITLE
Test PR. DO NOT MERGE

### PR DESCRIPTION
**Pull request by bearbin**

### CODE REVIEW

**Comment by bearbin** [comment]
Ooh, bearbot is starting to work.

**Comment by tigerw** [comment]
...
...
...


huh?

**Comment by bearbin** [comment]
Do you not see the bearbot comment above?

**Comment by madmaxoft** [comment]
Yeah, but the message is somewhat too generic - who is he talking to, out of all those people making commits?

**Comment by bearbin** [comment]
Bearbot is talking to the person creating the pull request. I was just testing with a blank contributors file which is why it fired for me.

**Comment by madmaxoft** [comment]
I think it should address the person specifically using @mention

**Pull request closed without merging**
