### PR TITLE
Bindings cleanup

### PR DESCRIPTION
**Pull request by madmaxoft**
Removed unused stuff from ToLua, and added generating some glue code instead of manually written functions.

### CODE REVIEW

**Comment by madmaxoft** [comment]
@tigerw I know you are against *.inc files, but I think this change is beneficial. Do you think you can survive this? It's rather unlikely that you'd ever need to use a debugger on those generated functions anyway, they're just glue code.

**Comment by madmaxoft** [comment]
@worktycho you mentioned some code generator, would this method (piggybacking on the bindings generator) be sufficient for you? Just provide another function next to `OutputLuaStateHelpers` in BindingsProcessor.lua.

**Comment by worktycho** [comment]
Not really. It would need another run of the parser as the methods generated aren't really connected to the lua bindings.

**Comment by tigerw** [comment]
No objections here.

**Comment by madmaxoft** [comment]
Ha, I was chasing the CI error in the CMake script, and it was in the CheckBasicStyle the whole time.

**Pull request merged**
