### PR TITLE
Testing - Less path calcs

### PR DESCRIPTION
**Pull request by SafwatHalaby**

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
No, no, no, bad, bad, bad. :P

**Comment by madmaxoft** [comment]
You need to update your `testing` branch, then cherry-pick the commit you want there from `master` and finally submit a PR.

**Comment by SafwatHalaby** [comment]
I already created a different commit with the same changes and merged it with `testing`, is that ok?

**Comment by madmaxoft** [comment]
I guess it is for now, although we'll see what it does when we finally want to merge master to testing, it might create a conflict.

**Comment by SafwatHalaby** [comment]
It's identical, I think git can handle it.

**Pull request closed without merging**
