### PR TITLE
Unify packetizer

### PR DESCRIPTION
**Pull request by madmaxoft**
Unified the two different `cPacketizer` classes inside the `cProtocol` descendants into a single shared class. The packetizer only writes the low-level datatypes, the high-level information (such as `cItem` data or mob metadata) is handled by the `cProtocol` descendants.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
This could mean we could possible add custom packets for Lua. Something like
```lua
ClientHandle:SendCustomPacket(
   function(a_Packetizer, a_ProtocolVer)
      -- Packet Data
   end
)

**Comment by SphinxC0re** [comment]
That would be a huge step in case of Forge mod compatibility

**Comment by jan64** [comment]
Or, plugin-based protocol support.

**Comment by madmaxoft** [comment]
Nah, I'm not willing to go there. And neither is Mojang - after all, we have the plugin channel packets.

**Comment by NiLSPACE** [comment]
But it would allow plugins to use more then just the "broadcastXXX" functions.

**Comment by jan64** [comment]
Of course, it could end up being a big mess, but i think it's worth it for the few creative uses that will most likely emerge.

**Comment by jan64** [comment]
Also, adding a raw incoming packet hook would be nice.
But, that could cause performance issues.

**Comment by madmaxoft** [comment]
Anyone against a merge?

**Comment by NiLSPACE** [comment]
I don't have any objections.

**Comment by tigerw** [comment]
Oh no, not the American 'z'!

:)

**Comment by SphinxC0re** [comment]
I like the 'z' :D

**Pull request merged**
