### PR TITLE
Command handling

### PR DESCRIPTION
**Pull request by madmaxoft**
Altogether improved the command handling in the plugin manager.

This mostly aims to implement support for the Aliases plugin, as well as fix bugs in the support code.

### CODE REVIEW

**Comment by worktycho** [comment]
C++ code looks good, but I can't comment on the lua.

**Comment by SphinxC0re** [comment]
2000!!! :tada:

**Comment by worktycho** [comment]
Not long till we hit a nice round 0x800 :)

**Comment by SphinxC0re** [comment]
# Yeah :)

**Comment by SphinxC0re** [comment]
0o4000

**Pull request merged**
