### PR TITLE
Made cLightingThread own its callbacks

### PR DESCRIPTION
**Pull request by worktycho**

### CODE REVIEW

**Comment by madmaxoft** [comment]
We do have a `UniquePtr` that should be used instead of the lengthy and underscore-y `std::unique_ptr`

**Comment by worktycho** [comment]
I personally thing the project typedefs are a barrier to newcomers. At least with the std types every c++ project has them. But with our typedefs, they need to be learned specially for our project.

**Comment by worktycho** [comment]
Merge or are you going to insist on UniquePtr.

**Comment by madmaxoft** [comment]
I'm too soft :P

**Pull request merged**
