### PR TITLE
Bed uses bottom two bits for direction not three

### PR DESCRIPTION
**Pull request by worktycho**

### CODE REVIEW

**Comment by madmaxoft** [comment]
There are more places in the cpp where the code checks three bits instead of two, you should fix all of them

**Comment by worktycho** [comment]
Fixed. Also I'm not sure what the &0xd is is doing in the set at the end.

**Comment by SafwatHalaby** [comment]
Offtopic but a bit relevant: 

>No magic numbers, use named constants

There are lots of magic numbers when it comes to meta values, and it's kind of ugly.

**Comment by jan64** [comment]
i believe these are not magic numbers, just bitmasks.

**Comment by worktycho** [comment]
I agree with that, but we've never worked out a good way of dealing with all the magic numbers. If only C++ bit-fields weren't terrible. It might be possible to do something with templates to improve the situation though.

**Comment by SafwatHalaby** [comment]
> i believe these are not magic numbers but bitmasks. 

Magic bitmasks then :P

**Comment by jan64** [comment]
if you convert them to binary, they aren't magic - they are actually readable. :P

**Pull request merged**
