### PR TITLE
Defing Clay to be handled with the OreHandler

### PR DESCRIPTION
**Pull request by jammet**

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Did you also test the changes to see if they work? ;)

**Comment by jammet** [comment]
I wouldn't know how to test these changes... I don't compile my own builds.

**Comment by madmaxoft** [comment]
Four commit for a single line change, and untested. Just... wow.

**Comment by jammet** [comment]
Well, I did say that I'm not a programmer. Several times. So, while I was
just trying to take some off your shoulders, and speed things up a little,
I failed. Sorry. :(
I'll stick to just reporting bugs if I find any.

**Comment by tigerw** [comment]
xoft, don't discourage people from contributing :P

It looks fine.

**Comment by madmaxoft** [comment]
Sorry, I had no such intention.

**Comment by madmaxoft** [comment]
I've squashed the commits and merged into master.

**Pull request closed without merging**
