### PR TITLE
Revert "Revert "PathFinder - smart pointers""

### PR DESCRIPTION
**Pull request by tigerw**
Reverts mc-server/MCServer#2024

Yo dawg...

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
Life is complicated...

**Comment by madmaxoft** [comment]
oh come on, the git history will look awful with such non-descriptive commit messages

**Comment by tigerw** [comment]
Pleeease?

**Comment by madmaxoft** [comment]
Merged manually with proper commit message and original author.

**Pull request closed without merging**
