### PR TITLE
More user friendly log file names

### PR DESCRIPTION
**Pull request by planetx**
Changed the format of the log file names to LOG-YYYY-MM-DD.txt for easier use by humans and scripts.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Not good - all log files from a single day are joined into one file.

**Comment by bearbin** [comment]
BTW, you need to link your github account to your git email address.

**Comment by planetx** [comment]
You only generate a single log file anyways.  This would make log file management easier.

**Comment by madmaxoft** [comment]
No, a new file is generated for each server run, and that's intentional.

**Pull request closed without merging**
