### PR TITLE
made underlying size variables constexpr

### PR DESCRIPTION
**Pull request by worktycho**
This makes the code standard compliant.
Previously we had got away with the non-compliant code because gcc and clang have an extension that allows the use of VLA's in c++ and visual studio has a bug/misfeature that allows const variables to be used in array declarations if they are initialized by a constant expression or by a const variable that is initialized in the same manner.

### CODE REVIEW

**Comment by madmaxoft** [comment]
MSVC2013 doesn't support `constexpr` yet.

**Comment by worktycho** [comment]
So we either need to require the Nov 2013 CTP or add the support for const vars in array initializes as a required extension.

**Comment by worktycho** [comment]
Or remove the variables or use an enum value instead of a constvar.

**Comment by madmaxoft** [comment]
I think I'd prefer the enum-based solution.

**Comment by worktycho** [comment]
I've implemented the enum based solution.

**Comment by madmaxoft** [comment]
I still don't understand what's wrong with the original code. I believe array bounds specified as const integers are perfectly valid C++ code.

**Comment by worktycho** [comment]
Looks like const variables are valid so long as they are initialised with a constant expression. However the constexpr change would of clarified things if MSVC had supported it.

**Comment by tigerw** [comment]
Can the branch be deleted?

**Pull request closed without merging**
