### PR TITLE
Updated MagicCarpet submodule

### PR DESCRIPTION
**Pull request by mathias-github**

### CODE REVIEW

**Comment by madmaxoft** [comment]
The commit message is completely misleading. Wat?

**Comment by mathias-github** [comment]
I used the latest commit message from the MagicCarpet repository, but I can change it if you prefer so.

**Comment by tigerw** [comment]
Probably an 'updated magiccarpet' would be fine.

**Comment by madmaxoft** [comment]
I think "Updated MagicCarpet submodule" is a better commit message, in the context of the entire repo.

**Pull request closed without merging**
