### PR TITLE
Added console input indicator

### PR DESCRIPTION
**Pull request by SphinxC0re**
I'm open for a discussion whether it should be a '>' or a '$' or something else.
It's currently a $

### CODE REVIEW

**Comment by worktycho** [comment]
This will rapidly disappear under all of the console logs.

**Comment by SphinxC0re** [comment]
Yeah it's only for input, you are right

**Comment by madmaxoft** [comment]
I don't think it's worth it - whenever the server outputs a new log to the console, the indicator line stays and a new one is appended below. Try running a debug-mode server, then walking past the edge of generated chunks. The input indicator gets mixed with generator logs.

**Comment by SphinxC0re** [comment]
That can all be fixed. The indicator is more about a good UX. I mention a point where the user can see that he can type something in that really does something would be pretty nice.

**Pull request closed without merging**
