### PR TITLE
Update COMPILING.md

### PR DESCRIPTION
**Pull request by Samvbnm**
Tell the reader to make sure they have the latest buildtools installed.

### CODE REVIEW

**Comment by bearbin** [comment]
The text should be outside of the code block.

**Comment by madmaxoft** [comment]
It's not "the latest" that you need, it's "g++ 4.8 or newer". For some platforms, the latest is 4.6, which just won't make it.

**Comment by Samvbnm** [comment]
Does the gcc version also matter or is that irrelevant?

**Comment by bearbin** [comment]
Nothing else really matters apart from gcc and g++.

**Pull request merged**
