### PR TITLE
Fixed player switching world bug

### LINKED ISSUE #1842: cPlayer:MoveToWorld does not broadcast event
When I was testing out a few of my plugins with some friends over LAN a day ago, we couldn't see each other when we were both moved to the same world using the cPlayer:MoveToWorld function.  I narrowed it down to this by using /portal.  Along with that, we could not pick up items after being moved.

### PR DESCRIPTION
**Pull request by NiLSPACE**
Fixed players not appearing/disappearing when traveling to a different world.
Fixes #1842

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Merge?

**Comment by tigerw** [comment]
If it works, why not.

**Comment by NiLSPACE** [comment]
It works for me. Maybe @DevToaster can confirm?

**Comment by DevToaster** [comment]
I'll do a compile and test run and see what happens.

**Comment by DevToaster** [comment]
Now I just noticed another problem.  :(  When a player dies and respawns, occasionally they may respawn as an invisible player.

**Comment by madmaxoft** [comment]
Is this thread-safe? This code is rather fragile in this sense.

**Comment by NiLSPACE** [comment]
@madmaxoft Should I try to move the `BroadcastSpawnEntity` function to the place where the player actualy is put into the world?

**Comment by NiLSPACE** [comment]
So it was thread-safe?

**Comment by madmaxoft** [comment]
I guess. No thread-related problems have been observed; you'd most likely hit the deadlock detector if there was a problem.

**Pull request merged**
