### PR TITLE
PF - Iron bars support

### PR DESCRIPTION
**Pull request by SafwatHalaby**

### CODE REVIEW

**Comment by bearbin** [comment]
Iron bars aren't fences though - they're only 1 block high.

**Comment by SafwatHalaby** [comment]
Don't they block mobs though?

**Comment by bearbin** [comment]
And if iron bars are included, glass panes should be also. 

And yes, they do block mobs, i didn't realise what function this was in.

**Comment by SafwatHalaby** [comment]
Thanks. I'll add glass panes too.

I'm planning to rewrite isSolid, by the way. It is not the right place for it and it can cause some issues in some fence setups.

**Comment by SafwatHalaby** [comment]
Wrong, wrong.
I just tested this on Vanilla, neither glass nor iron acts like a fence. Mobs can freely jump on them.

**Pull request closed without merging**
