### PR TITLE
PathFinder - Fixed Howaner's bug

### PR DESCRIPTION
**Pull request by SafwatHalaby**
Fixes [this](http://forum.mc-server.org/showthread.php?tid=1571&pid=19891#pid19891).

### CODE REVIEW

**Comment by madmaxoft** [comment]
I'd leave the assert at the top of the function, but check the `a_Chunk` instead. Or even better, pass the chunk as a reference, that can never be `nullptr`; then assign as `m_Chunk = &a_Chunk`

**Comment by SafwatHalaby** [comment]
Will do. Last time I tried this, there was a weird issue with Chunk references and the = operator. (But the ref might have been on the left hand, I'm not sure.)

**Comment by madmaxoft** [comment]
This looks good, merge if it compiles.

**Comment by SafwatHalaby** [comment]
Let me squash it first

**Comment by SafwatHalaby** [comment]
OK to merge.

**Pull request merged**
