### PR TITLE
Moved BroadcastChunkData over to cBroadcaster

### PR DESCRIPTION
**Pull request by worktycho**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Do we really need a new type for the two coords? Especially when it is only used to store them, there are no operations defined.

**Comment by madmaxoft** [comment]
You need to add the BroadcasterForwards.cpp to the list of ignored files in CheckBasicStyle.lua

**Comment by worktycho** [comment]
Theres a lot methods that work with such pairs, so I think a two element vector is worthwhile.

**Comment by worktycho** [comment]
Fixed check basic style

**Comment by madmaxoft** [comment]
Still not good. Can't the source file be generated in current source dir, instead of the build dir?

**Comment by worktycho** [comment]
I've found a better way of handling BroadcastChunkData, so I'm going to leave this for now.

**Pull request closed without merging**
