### PR TITLE
Fix Daylightsensor recipe

### PR DESCRIPTION
**Pull request by jammet**
Something like Woodslap^-1 didn't work here, so I split it up into individual recipes.

### CODE REVIEW

**Comment by madmaxoft** [comment]
That's weird, it should have worked.

**Comment by madmaxoft** [comment]
(Also, what's with the "slap"s? :)

**Comment by madmaxoft** [comment]
Ah, that would be because there are two wooden slabs in MC. The old one (`woodslab`) shared the block type with the stone and brick slabs, the new one (`woodenslab`) had different wood types. If you change the recipe to use the new one, it should work with `^1`.

**Comment by jammet** [comment]
I don't know, sometimes my grammar is just way off, and turns what would otherwise be completely boring into something stupid! XD

I'll test the woodenslaps thing on my server and if it works, I'll change it around here, too.

**Comment by jammet** [comment]
Nice! :)

**Pull request merged**
