### PR TITLE
Fix sapling probability.

### PR DESCRIPTION
**Pull request by bearbin**
Probability is 5% of leaves drop a sapling.

This should really be different for jungle leaves (2.5%) and the Fortune enchantment should increase the probability.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Does fortune really improve the probability? I thought it only worked on ores.

**Comment by bearbin** [comment]
This should fix #2046. And see the wiki for more info: http://minecraft.gamepedia.com/Sapling#Obtaining

**Comment by SafwatHalaby** [comment]
For [reference](url=http://minecraft.gamepedia.com/Sapling):
>When leaves are broken by any tool except shears, they will have a 5% chance of dropping a sapling. Jungle leaves instead have a 2.5% chance of dropping a sapling.

**Comment by SafwatHalaby** [comment]
I accidentally merged, this is not that much of a problem, jungle can be fixed on a seperate PR.

**Pull request merged**
