### PR TITLE
Fixed Valgrind problem (use of uninitialised value).

### PR DESCRIPTION
**Pull request by UltraCoderRU**
I think, additional array initialization will not be superfluous, because it's in chunk generation code. I apologize if I'm wrong.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Do you have an actual valgrind log to support this? Because I believe the initialization is not needed, the values are always overwritten.

**Comment by UltraCoderRU** [comment]
```
==26849== Conditional jump or move depends on uninitialised value(s)
==26849==    at 0xA573CA: cInterpolCell3D<Interp5Deg>::Move(int, int, int) (InterpolNoise.h:262)
==26849==    by 0xA5614B: cInterpolNoise<Interp5Deg>::Generate3D(float*, int, int, int, float, float, float, float, float, float) const (InterpolNoise.h:444)
==26849==    by 0xA5535A: cOctavedNoise<cInterpolNoise<Interp5Deg> >::Generate3D(float*, int, int, int, float, float, float, float, float, float, float*) const (OctavedNoise.h:132)
==26849==    by 0xA53EAE: cBiomalNoise3DComposable::GenerateNoiseArrayIfNeeded(int, int) (Noise3DGenerator.cpp:629)
==26849==    by 0xA54EA1: cBiomalNoise3DComposable::GenShape(int, int, unsigned char (&) [65536]) (Noise3DGenerator.cpp:797)
==26849==    by 0xA1D2E8: cComposableGenerator::DoGenerate(int, int, cChunkDesc&) (ComposableGenerator.cpp:165)
==26849==    by 0xA1BA51: cChunkGenerator::DoGenerate(int, int) (ChunkGenerator.cpp:295)
==26849==    by 0xA1B7F5: cChunkGenerator::Execute() (ChunkGenerator.cpp:275)
==26849==    by 0x8EB3E2: cIsThread::DoExecute() (IsThread.cpp:74)
==26849==    by 0x8EC93E: void std::_Mem_fn<void (cIsThread::*)()>::operator()<, void>(cIsThread*) const (in /home/ultracoder/work/MCServer/MCServer/MCServer_debug)
==26849==    by 0x8EC88E: void std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (functional:1732)
==26849==    by 0x8EC796: std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (functional:1720)
==26849==  Uninitialised value was created by a stack allocation
==26849==    at 0xA55BFA: cInterpolNoise<Interp5Deg>::Generate3D(float*, int, int, int, float, float, float, float, float, float) const (InterpolNoise.h:386)
...
==26849== Conditional jump or move depends on uninitialised value(s)
==26849==    at 0xA578D6: cInterpolCell2D<Interp5Deg>::Move(int, int) (InterpolNoise.h:101)
==26849==    by 0xA56706: cInterpolNoise<Interp5Deg>::Generate2D(float*, int, int, float, float, float, float) const (InterpolNoise.h:376)
==26849==    by 0xA55798: cOctavedNoise<cInterpolNoise<Interp5Deg> >::Generate2D(float*, int, int, float, float, float, float, float*) const (OctavedNoise.h:72)
==26849==    by 0xA5414B: cBiomalNoise3DComposable::GenerateNoiseArrayIfNeeded(int, int) (Noise3DGenerator.cpp:632)
==26849==    by 0xA54EA1: cBiomalNoise3DComposable::GenShape(int, int, unsigned char (&) [65536]) (Noise3DGenerator.cpp:797)
==26849==    by 0xA1D2E8: cComposableGenerator::DoGenerate(int, int, cChunkDesc&) (ComposableGenerator.cpp:165)
==26849==    by 0xA1BA51: cChunkGenerator::DoGenerate(int, int) (ChunkGenerator.cpp:295)
==26849==    by 0xA1B7F5: cChunkGenerator::Execute() (ChunkGenerator.cpp:275)
==26849==    by 0x8EB3E2: cIsThread::DoExecute() (IsThread.cpp:74)
==26849==    by 0x8EC93E: void std::_Mem_fn<void (cIsThread::*)()>::operator()<, void>(cIsThread*) const (in /home/ultracoder/work/MCServer/MCServer/MCServer_debug)
==26849==    by 0x8EC88E: void std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (functional:1732)
==26849==    by 0x8EC796: std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (functional:1720)
==26849==  Uninitialised value was created by a stack allocation
==26849==    at 0xA56334: cInterpolNoise<Interp5Deg>::Generate2D(float*, int, int, float, float, float, float) const (InterpolNoise.h:336)
```

**Comment by madmaxoft** [comment]
Alright, this is bad, but initializing to zero doesn't solve the core of the problem. The problem is that the code assumes that the values are **valid**; any initialization doesn't make the values valid, it only makes them known.

I think a better way to solve this would be to find out exactly when the values are invalid. This could be done by initializing all of them to a known "bad" number and then asserting on usage that they don't contain this number. Could you try that?

**Comment by UltraCoderRU** [comment]
I'm sorry. I can try it soon because I'm busy with coursework (in fact, I began to perform static and dynamic analysis of the project only for this work).

**Comment by worktycho** [comment]
@UltraCoderRU if you're working on static analysis of MCServer you may be interested in the Coverity scan issue list. We'd give you access if you requested it.

**Comment by UltraCoderRU** [comment]
http://pastebin.com/FJ62qehm
It seems ToX variable is beyond the scope of initialized memory:
```
...
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=7, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=7, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=13, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=13, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=13, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=30, SameX[x]=3, NumSameX=13, NumSameY=2, NumSameZ=2]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
FloorX[33] bad! [FromX=32, SameX[x]=1, NumSameX=26, NumSameY=3, NumSameZ=3]
...
```

**Comment by SphinxC0re** [comment]
Why not merge this?

**Comment by worktycho** [comment]
Because it doesn't actually fix the root issue which is that FloorX values are accessed in the loop which weren't filled in by CalcFloorFrac

**Comment by bearbin** [comment]
Closing, inactive and doesn't fix the root issue.

**Pull request closed without merging**
