### PR TITLE
Changed Nether composition to change the threshold from a cubic noise

### PR DESCRIPTION
**Pull request by NiLSPACE**
This will case some dense and open areas in the nether.

### CODE REVIEW

**Comment by madmaxoft** [comment]
I'd expect this to create somewhat visible boundaries between chunks, since the threshold is applied per-chunk. Is that so?

**Comment by NiLSPACE** [comment]
I didn't notice any since a difference of 100 threshold is hardly noticeable, but I'll do some further testing.

I did consider calculating the threshold for each column in the chunk, but I thought I Could save some performance by doing it this way.

**Comment by NiLSPACE** [comment]
After searching I found a few chunk borders, but they were really small. It did look a big awkward in some cases, so I guess I'll calculate the threshold for each column.

**Comment by NiLSPACE** [comment]
I'm now searching a better default value for `m_MaxThreshold`.  10000 doesn't seem to make big differences in the terrain.

**Comment by NiLSPACE** [comment]
I think this is done now

**Comment by madmaxoft** [comment]
I'll try this out

**Comment by madmaxoft** [comment]
Looks good enough. A bit too dense for my taste, but that can probably be tweaked further.

**Pull request merged**
