### PR TITLE
Buttons can be placed on the top and on the bottom face of a block

### PR DESCRIPTION
**Pull request by alexandreguertin**

### CODE REVIEW

**Comment by alexandreguertin** [comment]
Addesses issue #1756 .

**Comment by tigerw** [comment]
Google-test failed again, like on #1734.

**Comment by alexandreguertin** [comment]
Is that a known issue? How can i fix it?

**Comment by madmaxoft** [comment]
I've restarted the builds. No idea what happens in the Google test, for some reason there's no output from the tests. I question the need for such tests.

**Comment by madmaxoft** [comment]
I think the meta values are wrong, at least according to the wiki: http://minecraft.gamepedia.com/Button#Data_values
There's no mention of meta value 6 or 7.

**Comment by madmaxoft** [comment]
@alexandreguertin Any update on this?

**Comment by alexandreguertin** [comment]
I'll be working on it this weekend.

**Comment by madmaxoft** [comment]
Oh, you should have dropped a message, I didn't see this was updated. I guess it's now good for a merge.

**Pull request merged**
